theme: jekyll-theme-slate

# Site settings
title: Personal Homepage
description: This is qwawa's personal homepage
author: qwawa

# Build settings
theme: jekyll-theme-slate

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
