name: Latest Added File

on:
  push:
    branches:
      - main

jobs:
  latest-added-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest added file
        id: latest-file
        run: |
          git diff --name-only --diff-filter=A HEAD^..HEAD | head -n 1
          echo "::set-output name=latest_file::$(git diff --name-only --diff-filter=A HEAD^..HEAD | head -n 1)"

      - name: Show latest added file
        run: |
          echo "Latest added file: ${{ steps.latest-file.outputs.latest_file }}"
