name: Python Tests

on:
  push:
    paths:
      - 'src/code/*.py'

jobs:
  test:
    name: Test Python Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'  # Modify to the Python version you're using

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Add dependencies if necessary

      - name: Run tests
        run: pytest src/code  # Modify the path to match your test directory
