name: Print Commit File Name

on:
  push:
    branches:
      - main

jobs:
  print_commit_file_name:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Print Commit File Name
        id: commit_files
        run:
          file_names=$(git log -1 --name-only --pretty=format:"%h")
          echo "Commit File Names:"
          echo "$file_names"
