name: Notify File Push

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Display Pushed File Name
        run: |
          echo "Pushed File: ${{ github.event.head_commit.modified[0] }}"
