name: Print Pushed File Name
on:
  push:
    branches:
      - main

jobs:
  print-file-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print Pushed File Name
        run: |
          echo "Pushed file:"
          git diff-tree --no-commit-id --name-only -r ${{ github.sha }}
