name: Print Pushed File Name
on:
  push:
    branches:
      - main

jobs:
  print-file-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Print Pushed File Name
        run: |
          echo "Pushed files:"
          git show --name-only --pretty="" ${{ github.sha }} 코드 분석
