name: Notify File Push

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Display Pushed Files
        run: |
          echo "Pushed Files:"
          for file in ${{ github.event.head_commit.modified }}; do
            echo "- $file"
          done
